---
call: UpdateApplication
service: ElasticBeanstalk
tests:
  - expected: SampleApp
    op: eq
    path: Application.ApplicationName
  - expected: Default
    op: eq
    path: Application.ConfigurationTemplates.0
  - expected: 2010-11-17T19:26:20.410Z
    op: eq
    path: Application.DateCreated
  - expected: 2010-11-17T20:42:54.611Z
    op: eq
    path: Application.DateUpdated
  - expected: Another Description
    op: eq
    path: Application.Description
  - expected: New Version
    op: eq
    path: Application.Versions.0
