---
call: TerminateEnvironment
service: ElasticBeanstalk
tests:
  - expected: SampleApp
    op: eq
    path: ApplicationName
  - expected: SampleApp-jxb293wg7n.elasticbeanstalk.amazonaws.com
    op: eq
    path: CNAME
  - expected: 2010-11-17T03:59:33.520Z
    op: eq
    path: DateCreated
  - expected: 2010-11-17T17:10:41.976Z
    op: eq
    path: DateUpdated
  - expected: EnvDescrip
    op: eq
    path: Description
  - expected: |-
      elasticbeanstalk-SampleApp-1394386994.us-east-1.elb.amazon
      aws.com
    op: eq
    path: EndpointURL
  - expected: e-icsgecu3wf
    op: eq
    path: EnvironmentId
  - expected: SampleApp
    op: eq
    path: EnvironmentName
  - expected: Grey
    op: eq
    path: Health
  - expected: 32bit Amazon Linux running Tomcat 7
    op: eq
    path: SolutionStackName
  - expected: Terminating
    op: eq
    path: Status
  - expected: Version1
    op: eq
    path: VersionLabel
