---
call: CreateApplicationVersion
service: ElasticBeanstalk
tests:
  - expected: SampleApp
    op: eq
    path: ApplicationVersion.ApplicationName
  - expected: 2010-11-17T03:21:59.161Z
    op: eq
    path: ApplicationVersion.DateCreated
  - expected: 2010-11-17T03:21:59.161Z
    op: eq
    path: ApplicationVersion.DateUpdated
  - expected: description
    op: eq
    path: ApplicationVersion.Description
  - expected: amazonaws.com
    op: eq
    path: ApplicationVersion.SourceBundle.S3Bucket
  - expected: sample.war
    op: eq
    path: ApplicationVersion.SourceBundle.S3Key
  - expected: Version1
    op: eq
    path: ApplicationVersion.VersionLabel
