---
call: UpdateApplicationVersion
service: ElasticBeanstalk
tests:
  - expected: SampleApp
    op: eq
    path: ApplicationVersion.ApplicationName
  - expected: 2010-11-17T19:26:20.699Z
    op: eq
    path: ApplicationVersion.DateCreated
  - expected: 2010-11-17T20:48:16.632Z
    op: eq
    path: ApplicationVersion.DateUpdated
  - expected: New Release Description
    op: eq
    path: ApplicationVersion.Description
  - expected: awsemr
    op: eq
    path: ApplicationVersion.SourceBundle.S3Bucket
  - expected: sample.war
    op: eq
    path: ApplicationVersion.SourceBundle.S3Key
  - expected: New Version
    op: eq
    path: ApplicationVersion.VersionLabel
